services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - fastapi

  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"